name: Init

on:
  workflow_dispatch:

jobs:
  init:
    runs-on: ubuntu-20.04
    steps:
      - name: Install packages
        run: sudo apt install unzip
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          java-version: 16
          distribution: adopt
          architecture: x64
      - name: Build actions
        run: |
          git clone https://github.com/stream-pi/essential-actions
          cd essential-actions
          make build-all
      - name: Move actions to Default.zip
        run: |
          mv essential-actions/BuiltPlugins/ src/main/resources/com/stream_pi/server/
          cd src/main/resources/com/stream_pi/server/
          unzip Default.zip -d Default
          mv BuiltPlugins/* Default/Plugins/
          rm -r BuiltPlugins
          rm -rf Default.zip
          cd Default
          zip -r Default.zip *
          mv Default.zip ../
          cd ../
          rm -r Default
      - name: Saving new Default.zip
        uses: actions/upload-artifact@v2
        with:
          name: default-zip
          path: src/main/resources/com/stream_pi/server/Default.zip
      - name: Setup JavaFX
        run: |
          wget -P /tmp https://download2.gluonhq.com/openjfx/17/openjfx-17-ea+12_linux-x64_bin-sdk.zip
          unzip /tmp/openjfx-17-ea+12_linux-x64_bin-sdk.zip -d /tmp
      - name: Set Timezone
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Kolkata"
      - name: Build Jars
        run: |
          echo $(date +'%d-%m-%Y %H:%M:%S %Z') > src/main/resources/com/stream_pi/server/build-date
          echo Build Date/Time: cat src/main/resources/com/stream_pi/server/build-date
          mvn -X package
      - name: Save built jars
        uses: actions/upload-artifact@v2
        with:
          name: built-jars
          path: target/lib/*
      - name: Set Version
        run: |
          echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      - name: Calculate required modules
        run: |
          JDEPS_MODULES=$(jdeps --module-path $JAVAFX_SDK/:target/lib/ --print-module-deps --ignore-missing-deps target/lib/server-$VERSION.jar)
          JAVAFX_MODULES=javafx.media,
          EXTRA_MODULES=java.base,java.logging,java.net.http,java.scripting,jdk.jsobject,jdk.unsupported,jdk.unsupported.desktop,jdk.xml.dom,java.xml,java.management,jdk.localedata,java.sql,jdk.crypto.ec
          echo "REQ_MODULES=$EXTRA_MODULES,$JDEPS_MODULES,$JAVAFX_MODULES" >> $GITHUB_ENV
        env:
          JAVAFX_SDK: /tmp/javafx-sdk-17/lib/
      - name: Saving REQ_MODULES
        run: |
          echo $REQ_MODULES
          echo $REQ_MODULES > req_modules.txt
      - name: Uploading REQ_MODULES
        uses: actions/upload-artifact@v2
        with:
          name: req_modules
          path: req_modules.txt
      - name: Saving VERSION
        run: |
          echo $VERSION > version.txt
      - name: Uploading VERSION
        uses: actions/upload-artifact@v2
        with:
          name: version
          path: version.txt
